language: ruby
script: bundle exec rake

services:
  - mongodb

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - ruby-head

gemfile:
  - Gemfile.rails40
  - Gemfile.rails41
  - Gemfile.rails42

matrix:
  allow_failures:
    - rvm: ruby-head

sudo: false
